### ISSUE TITLE
Ideias de logo-tipo UNIAC

### ISSUE THREAD

**Issue by andre-lc-ferreira** [Universidade-Aberta-de-Computacao/uniac#10]
# IDEIAS DE LOGO

Aqui colocarei todas as ideias de logo-tipo da __UNIAC__. Caso tenham ideias, melhorias ou até mesmo correções, comente aqui embaixo, e coloque suas logos aqui também.

### Capas
![01Logo](https://user-images.githubusercontent.com/46267619/91087165-6b34f580-e626-11ea-841a-85a74b8d8f6a.png)

---

### Perfil

![Captura de Tela 2020-08-24 às 16 26 38](https://user-images.githubusercontent.com/46267619/91087343-afc09100-e626-11ea-80a3-6de96ed9b3e8.png)

![Captura de Tela 2020-08-24 às 16 27 00](https://user-images.githubusercontent.com/46267619/91087360-b3541800-e626-11ea-8dc7-74db4fc02d2d.png)

**Comment by brunosana** [comment]
![logo](https://user-images.githubusercontent.com/39919020/91230179-73159800-e701-11ea-80b3-7050efe59be0.png)

Criei essa aqui com algumas referências da internet. As asas para representar a liberdade e a fonte semelhante a que você usou, para referenciar as universidades :)

Ainda não defini as cores, então estou enviando em preto e branco xd

**Comment by andre-lc-ferreira** [comment]
@brunosana Essa logo ficou muito massa! Adorei mano! @rafaels88 O que a acha?

**Comment by brunosana** [comment]
Valeu @andre2l2 !
Ao longo do tempo irei melhorar. Já observei uns problemas de alinhamento e logo depois começar a testar umas cores

**Comment by brunosana** [comment]
![logo_b](https://user-images.githubusercontent.com/39919020/91307687-ab11ef00-e784-11ea-8cfa-5681b7a98fe8.png)
Mudei um pouco a parte de baixo, deixei ela mais reta, achei que combinou mais com a proposta e com a distribuição da marca.

**Comment by andre-lc-ferreira** [comment]
@brunosana Cara, muto bom! Realmente a versao antiga tava um puco torta. Mas ainda assim eu achei a versão com a parete inferior aredondada mias interessnte. Mas o que acha? 

Sobre as cores, tem um site chamado [coolors](https://coolors.co/palettes/trending) com diversas paletas de cores bem interesante.

**Comment by brunosana** [comment]
Show @andre2l2 . Não me decidi sobre qual me agradou mais. Quanto as cores, vou dar uma olhada nesse site. Estou testando algumas, em breve postarei aqui alguns experimentos 🤪
